ALTER TABLE users
ADD COLUMN IF NOT EXISTS username VARCHAR(50) UNIQUE,
ADD COLUMN IF NOT EXISTS bio TEXT;

ALTER TABLE user_settings
DROP CONSTRAINT IF EXISTS user_settings_theme_check;

ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS pomodoro_work_minutes INTEGER NOT NULL DEFAULT 25,
ADD COLUMN IF NOT EXISTS pomodoro_short_break_minutes INTEGER NOT NULL DEFAULT 5,
ADD COLUMN IF NOT EXISTS pomodoro_long_break_minutes INTEGER NOT NULL DEFAULT 15,
ADD COLUMN IF NOT EXISTS pomodoro_sessions_interval INTEGER NOT NULL DEFAULT 4,
ADD COLUMN IF NOT EXISTS auto_start_breaks BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS auto_start_work BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS count_break_time BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS countdown_default_minutes INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS stopwatch_target_hours INTEGER NOT NULL DEFAULT 2,
ADD COLUMN IF NOT EXISTS color_mode VARCHAR(16) NOT NULL DEFAULT 'dark',
ADD COLUMN IF NOT EXISTS color_theme VARCHAR(32) NOT NULL DEFAULT 'default',
ADD COLUMN IF NOT EXISTS master_volume INTEGER NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS alarm_volume INTEGER NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS notification_volume INTEGER NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS background_volume INTEGER NOT NULL DEFAULT 35,
ADD COLUMN IF NOT EXISTS alarm_preset VARCHAR(32) NOT NULL DEFAULT 'bells';
