ALTER TABLE topics ALTER COLUMN status DROP DEFAULT;
ALTER TABLE topics ALTER COLUMN status TYPE VARCHAR(50) USING status::text;
ALTER TABLE topics ALTER COLUMN status SET DEFAULT 'not_started';

ALTER TABLE assessments ALTER COLUMN type DROP DEFAULT;
ALTER TABLE assessments ALTER COLUMN type TYPE VARCHAR(50) USING type::text;
ALTER TABLE assessments ALTER COLUMN type SET DEFAULT 'other';

ALTER TABLE deadlines ALTER COLUMN type DROP DEFAULT;
ALTER TABLE deadlines ALTER COLUMN type TYPE VARCHAR(50) USING type::text;
ALTER TABLE deadlines ALTER COLUMN type SET DEFAULT 'assignment';

ALTER TABLE deadlines ALTER COLUMN urgency DROP DEFAULT;
ALTER TABLE deadlines ALTER COLUMN urgency TYPE VARCHAR(50) USING urgency::text;
ALTER TABLE deadlines ALTER COLUMN urgency SET DEFAULT 'medium';
